### ISSUE TITLE
Overlay setting command doesnt work

### ISSUE THREAD

**Issue by DynamicMiner** [OsuSync/ReplayPPDisplayer#1]
![image](https://user-images.githubusercontent.com/35213403/71790714-c486ef00-306c-11ea-933b-81473ab31159.png)
I have followed the process but still not working

**Comment by KedamaOvO** [comment]
overlay i (aka. o i) - inject overlay to osu on running.
overlay osu (aka. o osu) - open a osu process with overlay.
rtpp debug ture - set rtpp's debug mode to enable.
ortdp debug ture - set ortdp's debug mode to enable.
